#!/usr/bin/env bash

echo "== delete-object"

#Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

#Check for filename
if [ -z "$2" ]; then
    echo "There needs to be a file name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")

aws s3api delete-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY